wso2/performance-common

- components/jtl-splitter/src/main/java/org/wso2/performance/common/jtl/splitter/StatCalculator.java
- components/jtl-splitter/src/test/java/org/wso2/performance/common/jtl/splitter/StatCalculatorTest.java
- distribution/scripts/jmeter/create-summary-csv.sh
- distribution/scripts/jmeter/jmeter-server-start.sh
- distribution/scripts/jmeter/perf-test-common.sh
- distribution/scripts/netty-service/netty-start.sh
- distribution/scripts/setup/setup-common.sh
Improve error handling
* Validate inputs.
* Print more logs
* Fix load average columns
* Wait till Netty service starts
> Improve error handling

- distribution/scripts/jmeter/create-summary-csv.sh
- distribution/scripts/jmeter/perf-test-common.sh
Improve the summary results.
Create a test metadata file, which can be used to refer all details related to performance tests.
Update column names.
> Create test metadata file and update column names

- components/jtl-splitter/src/main/java/org/wso2/performance/common/jtl/splitter/JTLSplitter.java
- distribution/scripts/java/install-java.sh
- distribution/scripts/jmeter/create-summary-csv.sh
- distribution/scripts/jmeter/create-summary-markdown.py
- distribution/scripts/jmeter/install-jmeter.sh
- distribution/scripts/jmeter/jmeter-server-start.sh
- distribution/scripts/jmeter/perf-test-common.sh
- distribution/scripts/setup/setup-jmeter-client.sh
- distribution/scripts/setup/setup-jmeter.sh
- distribution/scripts/setup/setup-netty.sh
- pom.xml
Improve scripts
* Support Oracle JDK installation in JMeter and Netty instances
* Support creating summary markdown using a template
> Create summary markdown file from a template

- components/netty-http-echo-service/src/main/java/org/wso2/performance/common/netty/echo/EchoHttp2ServerHandler.java
- components/netty-http-echo-service/src/main/java/org/wso2/performance/common/netty/echo/Http2ServerInitializer.java
> Fix netty http2 backend

- distribution/scripts/docker/install-docker.sh
> This PR will add the installation script to install docker for a given instance
> Describe the solutions that this feature/fix will introduce to resolve the problems described above
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if the feature write-up is too long to paste here.
> Summary of user stories addressed by this change>
> Brief description of the new feature or bug fix as it will appear in the release notes
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact
> Link to the PR for changes to the training …
> Add docker runtime installation script

- components/netty-http-echo-service/src/main/java/org/wso2/performance/common/netty/echo/EchoHttpServerHandler.java
> Delay ctx.writeAndFlush

- distribution/scripts/cloudformation/cloudformation-common.sh
This is done in order to fix the Ballerina performance test temporarily. Will be reverted this, once the issue is identified.
> Add user email temporarily

- distribution/scripts/cloudformation/cloudformation-common.sh
Reverts wso2/performance-common#34
> Revert "Add user email temporarily"

- components/netty-http-echo-service/src/main/java/org/wso2/performance/common/netty/echo/EchoHttpServer.java
- components/netty-http-echo-service/src/main/java/org/wso2/performance/common/netty/echo/EchoHttpServerHandler.java
- components/netty-http-echo-service/src/main/java/org/wso2/performance/common/netty/echo/Http2OrHttpHandler.java
- components/netty-http-echo-service/src/main/java/org/wso2/performance/common/netty/echo/Http2ServerInitializer.java
> Describe the problems, issues, or needs driving this feature/fix and include links to related issues in the following format: Resolves issue1, issue2, etc.
> Describe the solutions that this feature/fix will introduce to resolve the problems described above
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if the feature write-up is too long to paste here.
> Summary of user stories addressed by this change>
> Brief description of the new feature or bug fix as it will appear in the release notes
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation …
> Update h2 content aggregate flag

- distribution/scripts/jmeter/perf-test-common.sh
- distribution/scripts/jmeter/run-backend-tests.sh
> Describe the problems, issues, or needs driving this feature/fix and include links to related issues in the following format: Resolves issue1, issue2, etc.
> Describe the solutions that this feature/fix will introduce to resolve the problems described above
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if the feature write-up is too long to paste here.
> Summary of user stories addressed by this change>
> Brief description of the new feature or bug fix as it will appear in the release notes
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation …
> Fix shell scripts to run as root

- distribution/scripts/jmeter/perf-test-common.sh
This PR reverts some fixes done by https://github.com/wso2/performance-common/pull/38
> Revert some shell scripts from executing as root

- distribution/scripts/jmeter/perf-test-common.sh
- distribution/scripts/jmeter/run-backend-tests.sh
This reverts https://github.com/wso2/performance-common/pull/38
> Revert #38

- distribution/scripts/jmeter/perf-test-common.sh
- distribution/scripts/jmeter/run-backend-tests.sh
This PR revert https://github.com/wso2/performance-common/pull/39 and fix the original bug which makes to revert it.
> Force netty-start to run as root user

- distribution/scripts/cloudformation/templates/common_perf_test_cfn.yaml
- distribution/scripts/jmeter/perf-test-common.sh
> Merge updates

- distribution/scripts/cloudformation/templates/common_perf_test_cfn.yaml
> Add ping for debugging

- distribution/scripts/cloudformation/templates/common_perf_test_cfn.yaml
> Add sleep until resources get warmup

- distribution/scripts/cloudformation/templates/common_perf_test_cfn.yaml
> Remove ping before sleep

- distribution/scripts/cloudformation/templates/common_perf_test_cfn.yaml
> Revert sleep until resource warmup

- .gitignore
- distribution/scripts/cloudformation/cloudformation-common.sh
- distribution/scripts/cloudformation/create-template.py
- distribution/scripts/jmeter/apimchart.py
- distribution/scripts/jmeter/create-charts.py
> [graphql] Update scripts for 4.3.0 release

- components/netty-http-echo-service/pom.xml
- distribution/scripts/cloudformation/cloudformation-common.sh
- distribution/scripts/cloudformation/create-template.py
- distribution/scripts/cloudformation/templates/common_perf_test_cfn.yaml
- distribution/scripts/jmeter/install-jmeter.sh
- distribution/scripts/jmeter/perf-test-common.sh
- pom.xml
$subject
> Describe the solutions that this feature/fix will introduce to resolve the problems described above
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if the feature write-up is too long to paste here.
> Summary of user stories addressed by this change>
> Brief description of the new feature or bug fix as it will appear in the release notes
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if applicable
> Type …
> Add changes to run jvm tests

- distribution/scripts/cloudformation/cloudformation-common.sh
- distribution/scripts/cloudformation/create-template.py
> Update scripts for APIM 4.3.0 release

- distribution/scripts/jmeter/create-sar-summary.py
https://github.com/wso2/api-manager/issues/3238
> [4.4.0] Fix non numeric mean bug

- distribution/scripts/jmeter/create-sar-summary.py
https://github.com/wso2/api-manager/issues/3238
> [4.4.0] [GraphQL] Fix non numeric mean bug

- pom.xml
Fix https://github.com/wso2/performance-common/issues/59
Related issue: https://github.com/netty/netty-tcnative/issues/648
> Upgrade tcnative-boringssl
